---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: rhbk-whitelist
spec:
  ipWhiteList:
    sourceRange:  
    - 40.113.125.116/32
    - 144.178.80.50/32
    - 144.178.80.54/32
    - 62.45.206.57/32
---
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: rhbk-transport
spec:
  insecureSkipVerify: true
  serverName: rhbk.{{ .Values.rhsso.clustername }}-backend.vdbinfra.nl
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: rhbk-ingress-http
  labels:
    app: rhbk
spec:
  entryPoints:
    - web
  routes:
    - match: Host("rhbk.{{ .Values.rhsso.clustername }}-backend.vdbinfra.nl")
      kind: Rule
      services:
        - name: rhbk
          kind: Service
          port: 8443
      middlewares:
        - name: traefik-https-redirect@kubernetescrd
        - name: rhbk-whitelist
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: rhbk-ingress-https
  labels:
    app: rhbk
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host("rhbk.{{ .Values.rhsso.clustername }}-backend.vdbinfra.nl")
      kind: Rule
      services:
        - name: rhbk
          kind: Service
          port: 8443
          scheme: https
          serversTransport: rhbk-transport
      middlewares:
        - name: rhbk-whitelist
  tls:
    secretName: le-prod-wildcard-cert