{{- if .Values.pgsql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgsql
  template:
    metadata:
      labels:
        app: pgsql
    spec:
      containers:
      - name: pgsql
        image: "{{ .Values.pgsql.image.repository }}:{{ .Values.pgsql.image.tag }}"
        imagePullSecrets:
          - name: docker-registry-secret
        env:
        - name: POSTGRES_DB
          value: "{{ .Values.pgsql.database.name }}"
        - name: POSTGRES_USER
          value: "{{ .Values.pgsql.user.name }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.pgsql.user.password }}"
        ports:
        - containerPort: 5432
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault

---
apiVersion: v1
kind: Service
metadata:
  name: pgsql
spec:
  selector:
    app: pgsql
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432

{{- end }}
