{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
        imagePullSecrets:
          - name: docker-registry-secret
        env:
        - name: POSTGRES_DB
          value: "{{ .Values.postgresql.database.name }}"
        - name: POSTGRES_USER
          value: "{{ .Values.postgresql.user.name }}"
        - name: POSTGRES_PASSWORD
          value: "{{ .Values.postgresql.user.password }}"
        ports:
        - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432

{{- end }}
