apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: rhbk
  name: rhbk
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: rhbk
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: rhbk
  type: ClusterIP