rhsso:
  image:
    repository: registry.redhat.io/rhbk/keycloak-rhel9
    tag: 22-6

  envs:
    admin:
      user: kcadmin
      password: cW5ID3ul5e

    db: 
      type: postgres
      url: pgsql.svc.local
      username: keycloak
      password: 64y7vYt7vh
      hostname: localhost

    # spi-import-single-file-file: ./realm-to-import.json
    # spi-import-single-file-realm-name: realm-name-other-than-master
    # spi-import-single-file-strategy: OVERWRITE_EXISTING #IGNORE_EXISTING OR OVERWRITE_EXISTING


# values.yaml
pgsql:
  enabled: true  # Set to false to disable pgsql deployment
  image:
    repository: postgres
    tag: latest
  database:
    name: keycloak
  user:
    name: keycloak
    password: 64y7vYt7vh