rhsso:
  image:
    repository: registry.redhat.io/rhbk/keycloak-rhel9
    tag: 22-6

  envs:
    admin:
      user: rhbkadmin
      password: cW5ID3ul5e

    db: 
      type: postgres
      url: jdbc:postgresql://rhbk-postgres.rhbk/vdb
      username: vdb
      password: vdb
      # hostname: localhost

    # spi-import-single-file-file: ./realm-to-import.json
    # spi-import-single-file-realm-name: realm-name-other-than-master
    # spi-import-single-file-strategy: OVERWRITE_EXISTING #IGNORE_EXISTING OR OVERWRITE_EXISTING

pgsql:
  enabled: false  # Set to false to disable pgsql deployment
  image:
    repository: postgres
    tag: latest
  database:
    name: vdb
    data: /var/lib/postgresql/data/pgdata
  user:
    name: vdb
    password: vdb