rhsso:
  image:
    repository: registry.redhat.io/rhbk/keycloak-rhel9
    tag: 22-6

  envs:
    admin:
      user: rhbkadmin
      password: cW5ID3ul5e

    db: 
      type: postgres
      url: jdbc:postgresql://rhbk-postgres.rhbk/vdb
      username: vdb
      password: vdb

  clustername: acce  
pgsql:
  enabled: false  # Set to false to disable pgsql deployment
  image:
    repository: postgres
    tag: latest
  database:
    name: vdb
    data: /var/lib/postgresql/data/pgdata
  user:
    name: vdb
    password: vdb